name: master amd64 - Build and Push

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Version
        id: version
        run: |
          ver=`curl -s https://raw.githubusercontent.com/misskey-dev/misskey/master/package.json | jq -r '.version'`
          echo "::set-output name=VER::$ver"
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: misskey-dev/misskey
          ref: master
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - 
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/misskey:latest
            ghcr.io/${{ github.repository_owner }}/misskey:${{ steps.version.outputs.VER }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

