name: develop - Build and Push

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Version
        id: version
        run: |
          ver=`curl -s https://raw.githubusercontent.com/minetaro12/misskey/docker-develop/package.json | jq -r '.version'`
          echo "::set-output name=VER::$ver"
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: minetaro12/misskey
          ref: docker-develop
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/misskey-develop:latest
            ghcr.io/${{ github.repository_owner }}/misskey-develop:${{ steps.version.outputs.VER }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

