name: dolphin - Build and Push

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          repository: mei23/dolphin
          ref: mei-dolphin
      -
        name: Get Version
        id: version
        run: |
          echo "ver=1.4.0-$(TZ=Asia/Tokyo date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dolphin:latest
            ghcr.io/${{ github.repository_owner }}/dolphin:${{ env.ver }}